### PR TITLE
Added rule manager which allows combining multiple rules using AND and OR.

### PR DESCRIPTION
**Pull request by bytebutcher**
Hi sunny0day,
i was in the process of writing my own "Auto-Drop requests" burp extension when i realized you already wrote one :+1:  I really liked your approach. So i've used it for quite some time. However, i found it quite challenging to manage a multitude of "rules" with a single regular expression. So i thought - why not add some kind of rule-manager which allows  adding/editing/removing and reordering rules. While in the process i also added the capability to drop requests based on headers, cookies, file extensions, parameters or the whole request. 
I hope I did not went overboard with all the changes and hope you will love these new additions to your code :) If you want to try it out you can either build the extension using gradle or download the current version from https://github.com/bytebutcher/burp-auto-drop/releases
Best regards,
bb

### CODE REVIEW

**Comment by sunny0day** [comment]
Hi bb, thanks a lot for your PR. I see you are very skilled in Java, your changes are great! I'm not a Java developer so I'm a bit overwhelmed.

I have a few questions, if you don't mind me asking:

1. Do you experience any performance degradation when using multiple regexes? I know that multiple regexes are slower than combining multiple in one. Of course I do agree with you that the multiple rules make things easier to work with! :+1: 
1. Is there a reason you haven't uploaded the JAR file to your repo? I have trouble building the project in Eclipse, e.g. because the `burp` deps are now missing.
1. I'm a bit unsure about the namespace 'bytebutcher' when it's merged to this repo. Do you have any thoughts on that?

I look forward testing your changes! Thanks a lot for sharing so much code, documentation, and screenshots! :heart:

**Comment by bytebutcher** [comment]
Hi sunny0day,
thanks for your quick response! Regarding your questions:
1. I made sure to parse requests only when it is required and then only once (see InterceptedProxyMessageWrapper-->getRequestInfo()). However, the Pattern for each regex rule is compiled everytime a new message is received. Now that you mention it, it would be quite easy to precompile the rules and recompile them everytime the rules change. I will definitely do that!
2. Oh, sorry, there was an error while uploading the jar file. I've reuplaoded it:
https://github.com/bytebutcher/burp-auto-drop/releases/tag/1.0
3. Sure, I'm happy to change it. Any proposals?

**Comment by bytebutcher** [comment]
Pattern-matching should now be even faster. Rules are now being reused for each incoming message. I've updated the jar-file, too:
* https://github.com/bytebutcher/burp-auto-drop/releases/tag/1.0

**Comment by sunny0day** [comment]
@bytebutcher I was able to build the .jar now, and played a bit with the changes you made. Really nice work! :muscle: I like that it's able to log requests that were dropped, and that there is a context menu now to easily add entries.

For usability, the "Match Condition" field in the 'Add "Auto-Drop Request" rule' dialog should be a bit bigger, but that can be improved later on.

Regarding the namespace, let's leave it as it is. I mean, it's great that you've put a lot of energy in this!

Thanks again!

**Pull request merged**
